### ISSUE TITLE
Tenant-side API allows storage clients to submit dataset locations, define storage provider policies, and track onboarding progress.

### ISSUE THREAD

**Issue by xmcai2016** [data-preservation-programs/spade#10]
```[tasklist]
### Tasks
- [ ] https://github.com/data-preservation-programs/spade/issues/15
- [ ] https://github.com/data-preservation-programs/spade/issues/16
- [ ] https://github.com/data-preservation-programs/spade/issues/14
- [ ] https://github.com/data-preservation-programs/spade/issues/33
```

- virtually all tenants come through
    - including set up for new tenants
- main purpose:
    - tenant side: policy CRUD
    - broker side: per tenant policies, per tenant SP eligibility tuning
- handles SP dynamic eligibility per tenant
    - updating the per SP ID eligibility per tenant policy at a given point in time
    - aggregating the inputs from KY-SP + reputation service

ETA: 2023-11-16

**Comment by xmcai2016** [comment]
Spec: https://www.notion.so/ecosystem-wg/Tenant-Services-Design-V1-WIP-36d56624eaed4101b83de64ceb40bd11?pvs=4

**Comment by xmcai2016** [comment]
API workspace: https://www.notion.so/ecosystem-wg/WIP-Tenant-side-APIs-4ca6a5c2c2434a6ab37a6d6e2ef11515?pvs=4

**Comment by anjor** [comment]
@xmcai2016 will you continue working on this while @jcace is on vacation + fil-vegas (till Oct 7th)? If so, can we reassign it to you for now?

**Comment by xmcai2016** [comment]
Assigning back to @jcace to work on implementation.
