### ISSUE TITLE
Scope out requirements for Deal Oracle

### ISSUE THREAD

**Issue by xmcai2016** [data-preservation-programs/spade#13]
Gather requirements from Riba and Xinan around the functional requirements for the new Deal Oracle service.

- Is the Oracle just Spade specific, or general?
- Likely want to have a publicly available API, with possible paywall for users

Possible function points:
- [ ] Define Deal monitoring functions
- [ ] Retrieval bot, Singularity v1/v2 functions

Update:

Per @Xinan's [slack thread](https://filecoinproject.slack.com/archives/C03UVDVVCDR/p1691166707841199?thread_ts=1691166042.319549&cid=C03UVDVVCDR)

> If you're talking about deal states. I have it in multiple places

> https://github.com/data-preservation-programs/market-deal-importer/blob/main/lib.ts A JS implementation and consumed by filplus-checker
> https://github.com/data-preservation-programs/singularity/blob/main/service/dealtracker/dealtracker.go Go implementation and runs by Singularity end user
> https://github.com/data-preservation-programs/RetrievalBot/blob/main/integration/statemarketdeals/main.go Go implementation and runs by Retrieval Bot

ETA: 2024-01-31
```[tasklist]
### Tasks
- [ ] Requirements Document for Deal Oracle for Spade
- [ ] Requirements Document for Deal Oracle for Singularity
```

**Comment by 10d9e** [comment]
[Draft Design](https://www.notion.so/ecosystem-wg/Software-Design-Specification-Data-Oracle-Subsystem-0b3732fca168420ebd2eebb6be64e6e8)

**Comment by anjor** [comment]
Let's aim to have alignment on the execution plan in a week's time (Sept 21st) -- which will be midpoint for this sprint.

@xinaxu @ribasushi will need your inputs on the above doc.

**Comment by 10d9e** [comment]
per conversation Sept 20, this item is blocked until @ribasushi has cycles to provide requirements

**Comment by jcace** [comment]
closing - out of scope as we'll use the one bundled as part of spade broker for now.
