### ISSUE TITLE
[Starmap] Spade Roadmap

### ISSUE THREAD

**Issue by xmcai2016** [data-preservation-programs/spade#19]
ETA: 2023-10-31

```[tasklist]
### Tasks
- [ ] https://github.com/data-preservation-programs/spade/issues/10
- [ ] https://github.com/data-preservation-programs/spade/issues/4
- [ ] https://github.com/data-preservation-programs/spade/issues/6
- [ ] https://github.com/data-preservation-programs/spade/issues/8
- [ ] https://github.com/data-preservation-programs/spade/issues/7
- [ ] https://github.com/data-preservation-programs/spade/issues/5
- [ ] https://github.com/data-preservation-programs/spade/issues/2
- [ ] https://github.com/data-preservation-programs/RetrievalBot/issues/45
- [ ] https://github.com/data-preservation-programs/spade-reputation-service/issues/2
- [ ] https://github.com/data-preservation-programs/spade/issues/40
```
