### ISSUE TITLE
Tenant-side webapp provides easy UX to interact with Spade

### ISSUE THREAD

**Issue by xmcai2016** [data-preservation-programs/spade#4]
[More detailed spec on [Notion](https://www.notion.so/ecosystem-wg/Spade-Tenant-App-4f311af1171248f8b7074f7ec03cf1c0?pvs=4)]
- layered on top of the tenant-service API experience
- account management
- wallet sign in
- tracking performance
ETA: 2024-06-01

```[tasklist]
### Tasks
- [ ] https://github.com/data-preservation-programs/spade/issues/20
- [ ] https://github.com/data-preservation-programs/spade/issues/23
- [ ] https://github.com/data-preservation-programs/spade/issues/27
- [ ] https://github.com/data-preservation-programs/spade/issues/24
- [ ] https://github.com/data-preservation-programs/spade/issues/25
- [ ] https://github.com/data-preservation-programs/spade/issues/26
- [ ] https://github.com/data-preservation-programs/spade/issues/28
- [ ] https://github.com/data-preservation-programs/spade/issues/12
```

**Comment by xmcai2016** [comment]
@orvn this is the Epic for Spade Tenant App. It's still WIP but feel free to leave comments / feedback here & on the Notion spec linked above!

**Comment by jcace** [comment]
Update feb 2024 - moving back to TODO: will potentially pick back up again if we determine we should build out the tenant UX.
