### ISSUE TITLE
[Epic] Spade Retrieval Bot Foundation

### ISSUE THREAD

**Issue by jcace** [data-preservation-programs/spade#46]
- Integrate the Spade reputation service with the ground control retrieval db 
```[tasklist]
### Tasks
- [ ] https://github.com/data-preservation-programs/spade-reputation-service/issues/3
- [ ] https://github.com/data-preservation-programs/spade-reputation-service/issues/1
- [ ] https://github.com/data-preservation-programs/spade/issues/38
- [ ] https://github.com/data-preservation-programs/RetrievalBot/issues/32
- [ ] https://github.com/data-preservation-programs/RetrievalBot/issues/45
- [ ] https://github.com/data-preservation-programs/spade-reputation-service/issues/7
- [ ] https://github.com/data-preservation-programs/spade/issues/34
- [ ] https://github.com/data-preservation-programs/spade/issues/35
- [ ] https://github.com/data-preservation-programs/spade/issues/39
- [ ] https://github.com/data-preservation-programs/spade/issues/36
- [ ] https://github.com/data-preservation-programs/spade/issues/37
```
ETA: 2023-11-15

**Comment by anjor** [comment]
On hold till @jcace comes back from holiday + fil-vegas (Oct 7th).
